# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AUV_2020.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1585, 896)
        Form.setAutoFillBackground(False)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 400, 321, 471))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 70, 121, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 170, 121, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 290, 81, 41))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setGeometry(QtCore.QRect(50, 290, 101, 41))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setGeometry(QtCore.QRect(50, 390, 101, 41))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 390, 81, 41))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 321, 371))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(100, 80, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 210, 101, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 10, 721, 861))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(180, 470, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_36.setGeometry(QtCore.QRect(300, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(16)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setGeometry(QtCore.QRect(180, 580, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_41.setGeometry(QtCore.QRect(300, 590, 81, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(16)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 40, 101, 91))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 350, 91, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 350, 91, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 350, 91, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 760, 201, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox.setGeometry(QtCore.QRect(420, 240, 101, 51))
        self.spinBox.setMaximum(200)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(420, 160, 101, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.verticalSlider.setGeometry(QtCore.QRect(540, 20, 141, 831))
        self.verticalSlider.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setSingleStep(2)
        self.verticalSlider.setPageStep(5)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(130, 90, 191, 131))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(39, 660, 461, 61))
        self.horizontalSlider.setMinimum(50)
        self.horizontalSlider.setMaximum(400)
        self.horizontalSlider.setSingleStep(50)
        self.horizontalSlider.setPageStep(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(1100, 10, 461, 861))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 91, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(180, 90, 91, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(320, 90, 91, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(100, 190, 91, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(250, 190, 91, 41))
        self.label_6.setObjectName("label_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setGeometry(QtCore.QRect(10, 240, 131, 41))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(220, 240, 81, 41))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_31.setGeometry(QtCore.QRect(330, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(230, 360, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_33.setGeometry(QtCore.QRect(330, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_29.setGeometry(QtCore.QRect(140, 370, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_28.setGeometry(QtCore.QRect(140, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(230, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setGeometry(QtCore.QRect(10, 360, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_30.setGeometry(QtCore.QRect(330, 370, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setGeometry(QtCore.QRect(10, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(10, 580, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_54 = QtWidgets.QLabel(self.groupBox_6)
        self.label_54.setGeometry(QtCore.QRect(10, 430, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_35.setGeometry(QtCore.QRect(140, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        self.label_55.setGeometry(QtCore.QRect(10, 510, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_46.setGeometry(QtCore.QRect(140, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_46.setFont(font)
        self.lineEdit_46.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_45.setGeometry(QtCore.QRect(140, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_45.setFont(font)
        self.lineEdit_45.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setGeometry(QtCore.QRect(20, 650, 131, 41))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_38.setGeometry(QtCore.QRect(140, 800, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_48 = QtWidgets.QLabel(self.groupBox_6)
        self.label_48.setGeometry(QtCore.QRect(20, 720, 131, 41))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_40.setGeometry(QtCore.QRect(140, 730, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_46 = QtWidgets.QLabel(self.groupBox_6)
        self.label_46.setGeometry(QtCore.QRect(20, 790, 131, 41))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_37.setGeometry(QtCore.QRect(140, 660, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_44.setGeometry(QtCore.QRect(330, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_43.setGeometry(QtCore.QRect(330, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(230, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(230, 510, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(240, 650, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 660, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_32.setGeometry(QtCore.QRect(330, 800, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(330, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(240, 720, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(240, 580, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 730, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_47 = QtWidgets.QLabel(self.groupBox_6)
        self.label_47.setGeometry(QtCore.QRect(250, 790, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(60, 50, 50, 50))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(200, 50, 50, 50))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(340, 50, 50, 50))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(130, 140, 50, 50))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(270, 140, 50, 50))
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "速度测量"))
        self.pushButton_8.setText(_translate("Form", "起点开始"))
        self.pushButton_9.setText(_translate("Form", "终点结束"))
        self.lineEdit_4.setText(_translate("Form", "0.0"))
        self.label_44.setText(_translate("Form", "GPS路程"))
        self.label_57.setText(_translate("Form", "GPS速度"))
        self.lineEdit_5.setText(_translate("Form", "0.0"))
        self.groupBox_3.setTitle(_translate("Form", "开/关"))
        self.pushButton.setText(_translate("Form", "打开"))
        self.pushButton_2.setText(_translate("Form", "关闭"))
        self.groupBox_5.setTitle(_translate("Form", "控制端"))
        self.label_45.setText(_translate("Form", "X-滑台"))
        self.lineEdit_36.setText(_translate("Form", "95"))
        self.label_50.setText(_translate("Form", "Y-滑台"))
        self.lineEdit_41.setText(_translate("Form", "60"))
        self.pushButton_3.setText(_translate("Form", "急停"))
        self.pushButton_4.setText(_translate("Form", "前进"))
        self.pushButton_5.setText(_translate("Form", "左转"))
        self.pushButton_6.setText(_translate("Form", "右转"))
        self.pushButton_7.setText(_translate("Form", "设定模式"))
        self.pushButton_11.setText(_translate("Form", "复位"))
        self.label_25.setText(_translate("Form", "1"))
        self.groupBox_6.setTitle(_translate("Form", "显示端"))
        self.label_2.setText(_translate("Form", "进水灯"))
        self.label_3.setText(_translate("Form", "姿态灯"))
        self.label_4.setText(_translate("Form", "运行灯"))
        self.label_5.setText(_translate("Form", "急停灯"))
        self.label_6.setText(_translate("Form", "触底灯"))
        self.label_35.setText(_translate("Form", "保护板"))
        self.label_38.setText(_translate("Form", "百分比"))
        self.lineEdit_31.setText(_translate("Form", "0.0"))
        self.label_39.setText(_translate("Form", "温度"))
        self.lineEdit_33.setText(_translate("Form", "0.0"))
        self.lineEdit_29.setText(_translate("Form", "0.0"))
        self.lineEdit_28.setText(_translate("Form", "0.0"))
        self.label_42.setText(_translate("Form", "功率"))
        self.label_37.setText(_translate("Form", "电流"))
        self.lineEdit_30.setText(_translate("Form", "0.0"))
        self.label_36.setText(_translate("Form", "电压"))
        self.label_43.setText(_translate("Form", "电机温度"))
        self.label_54.setText(_translate("Form", "电机转速"))
        self.lineEdit_35.setText(_translate("Form", "0"))
        self.label_55.setText(_translate("Form", "控制器温度"))
        self.lineEdit_46.setText(_translate("Form", "0"))
        self.lineEdit_45.setText(_translate("Form", "0"))
        self.label_33.setText(_translate("Form", "鱼尾位置"))
        self.lineEdit_38.setText(_translate("Form", "0.0"))
        self.label_48.setText(_translate("Form", "摆尾频率"))
        self.lineEdit_40.setText(_translate("Form", "0.0"))
        self.label_46.setText(_translate("Form", "下潜深度"))
        self.lineEdit_37.setText(_translate("Form", "0.0"))
        self.lineEdit_44.setText(_translate("Form", "0.0"))
        self.lineEdit_43.setText(_translate("Form", "0.0"))
        self.label_40.setText(_translate("Form", "滑台X"))
        self.label_41.setText(_translate("Form", "滑台Y"))
        self.label_7.setText(_translate("Form", "俯仰角"))
        self.lineEdit_2.setText(_translate("Form", "0.0"))
        self.lineEdit_32.setText(_translate("Form", "0.0"))
        self.lineEdit.setText(_translate("Form", "0.0"))
        self.label_8.setText(_translate("Form", "偏航角"))
        self.label_9.setText(_translate("Form", "横滚角"))
        self.lineEdit_3.setText(_translate("Form", "0.0"))
        self.label_47.setText(_translate("Form", "速度"))
        self.label_10.setText(_translate("Form", "1"))
        self.label_11.setText(_translate("Form", "2"))
        self.label_12.setText(_translate("Form", "3"))
        self.label_13.setText(_translate("Form", "4"))
        self.label_14.setText(_translate("Form", "5"))

